[book]
authors = ["Start9"]
language = "en"
src = "src"
title = "StartOS Docs"

[build]
build-dir = "docs"

[output]

[output.html]
sidebar-header-nav = false
admonitions = true
no-section-label = true
default-theme = "ayu"
preferred-dark-theme = "ayu"
additional-css = ["./theme/docs-agent.css", "./theme/youtube.css"]
additional-js = ["./theme/docs-agent-init.js", "./theme/docs-agent.js", "./theme/youtube.js"]
git-repository-url = "https://github.com/start9labs/docs"
edit-url-template = "https://github.com/start9labs/docs/edit/master/{path}"
site-url = "./"

[output.html.fold]
enable = true
level = 0
